LAB2INT = {
    "Pause": 0,
    "Move to the left": 1,
    "Undo: Rotate arm anti-clockwise": 2, 
    "No: Head shake": 3, 
    "Thumbs down": 4, 
    "I will follow you": 5, 
    "Do Nothing": 6, 
    "Watch out": 7, 
    "Slow down": 8, 
    "Thumbs up": 9, 
    "Pointing: Area": 10, 
    "Resume": 11, 
    "Repeat: Rotate arm clockwise": 12, 
    "Follow me": 13, 
    "Yes: Head nod": 14, 
    "Come forward": 15, 
    "Move to the right": 16, 
    "Move backward": 17, 
    "Watch me": 18, 
    "Doing something else": 19, 
    "Handwave": 20, 
    "Start": 21, 
    "Pointing: Object": 22, 
    "Speed up": 23, 
    "Stop": 24
}

GESTURE_THRESHOLDS = {
    "Pause": 0.6,
    "Move to the left": 0.4,
    "Undo: Rotate arm anti-clockwise": 0.2, 
    "No: Head shake": 0.9, 
    "Thumbs down": 0.5, 
    "I will follow you": 0.5, 
    "Watch out": 0.3, 
    "Slow down": 0.7, 
    "Thumbs up": 0.5, 
    "Pointing: Area": 0.4, 
    "Resume": 0.5, 
    "Repeat: Rotate arm clockwise": 0.4, 
    "Follow me": 0.5, 
    "Yes: Head nod": 0.7, 
    "Come forward": 0.6, 
    "Move to the right": 0.4, 
    "Move backward": 0.7, 
    "Watch me": 0.5, 
    "Handwave": 0.5, 
    "Start": 0.5, 
    "Pointing: Object": 0.5, 
    "Speed up": 0.5, 
    "Stop": 0.8
}

"""
GESTURE_THRESHOLDS = {
    "Start": .7,
    "Stop": .4,
    "Handwave": .6,
    "Pointing: Object": .5,
    "Do Nothing": 0,
    "Come forward": 22,
    "Doing something else": 26,
    "Follow me": 12,
    "Give an Item": 7,
    "I will follow you": 11,
    "Move backward": 25,
    "Move to the left": 24,
    "Move to the right": 23,
    "No: Head shake": 21,
    "Pause": 14,
    "Pointing: Area": 5,
    "Receive an Item": 6,
    "Repeat: Rotate arm clockwise": 8,
    "Resume": 13,
    "Slow down": 17,
    "Speed up": 16,
    "Thumbs down": 19,
    "Thumbs up": 18,
    "Undo: Rotate arm anti-clockwise": 9,
    "Watch me": 10,
    "Watch out": 15,
    "Yes: Head nod": 20,    
}
"""