LAB2INT = {
    "Air Jump Rope": 0,
    "Arm Circles": 1,
    "Bicycle Crunches": 2,
    "Bird Dog": 3,
    "Boxing Bounce Steps": 4,
    "Boxing: Cross": 5,
    "Boxing: Cross-Hook": 6,
    "Boxing: Cross-Uppercut": 7,
    "Boxing: Hook Left": 8,
    "Boxing: Hook Left-Hook Right": 9,
    "Boxing: Hook Left-Uppercut Right": 10,
    "Boxing: Hook Right": 11,
    "Boxing: Hook Right-Uppercut Left": 12,
    "Boxing: Jab": 13,
    "Boxing: Jab-Cross": 14,
    "Boxing: Jab-Hook": 15,
    "Boxing: Jab-Uppercut": 16,
    "Boxing: Uppercut Left": 17,
    "Boxing: Uppercut Left-Uppercut Right": 18,
    "Boxing: Uppercut Right": 19,
    "Bunny Hops": 20,
    "Burpees": 21,
    "Butt Kickers": 22,
    "Cat-Cow Pose": 23,
    "Child Pose": 24,
    "Cobra Pose": 25,
    "Deltoid Stretch (left)": 26,
    "Deltoid Stretch (right)": 27,
    "Doing nothing": 28,
    "Doing other things": 29,
    "Donkey Kicks": 30,
    "Downward Dog": 31,
    "Floor Touches": 32,
    "Garland Pose": 33,
    "Good Mornings": 34,
    "Halfway Lifts": 35,
    "High Knees": 36,
    "Hip Abductions": 37,
    "Hip Circles": 38,
    "Jump Lunges": 39,
    "Jumping Jacks": 40,
    "Jumping Oblique Crunches": 41,
    "Knee Circles": 42,
    "Low Lunge Pose": 43,
    "Lunges (alternating)": 44,
    "Lunges (stationary)": 45,
    "Mountain Climbers": 46,
    "Moving Plank": 47,
    "Neck Rolls": 48,
    "No person visible": 49,
    "Plank": 50,
    "Plank Taps": 51,
    "Puddle Jumps": 52,
    "Pushups": 53,
    "Quad Stretch (left)": 54,
    "Quad Stretch (right)": 55,
    "Quadruped Thoracic Spine Rotations": 56,
    "Quick Feet": 57,
    "Raised Leg Circles": 58,
    "Reverse Crunches": 59,
    "Shoulder Gators": 60,
    "Side-Plank": 61,
    "Snowboarders": 62,
    "Squat Jacks": 63,
    "Squat Jumps": 64,
    "Squat Kicks": 65,
    "Squat Punches": 66,
    "Squats": 67,
    "Standing Kicks (alternating)": 68,
    "Standing Kicks (left)": 69,
    "Standing Kicks (right)": 70,
    "Standing Oblique Crunches": 71,
    "The Hundred": 72,
    "Toe Toucher": 73,
    "Tree Pose": 74,
    "Tricep Stretch": 75,
    "Upward Salute": 76,
    "Warrior 1 (left)": 77,
    "Warrior 1 (right)": 78,
    "Warrior 2 (left)": 79,
    "Warrior 2 (right)": 80
}

INT2LAB = {value: key for key, value in LAB2INT.items()}
